{{- if .Values.sharedSecretsEnabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:  
  name: {{ .Values.databaseSecretName }}
  namespace:  {{ .Release.Namespace }}
spec:
  encryptedData:
    connectionstring: {{ .Values.databaseConnectString }}
  template:
    data: null
    metadata:      
      name: {{ .Values.databaseSecretName }}
      namespace:  {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
{{- end }}
